[tasks.boeupdater-init]
workspace = false
condition = { files_not_exist = [
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/auctions.cbor.zlib",
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/assets.cbor.zlib"
   ] }
command = "cargo"
args = [
  "run",
  "-p",
  "shylock-parser",
  "--release",
  "--bin",
  "boeupdater",
  "--",
  "-d",
  "./shylock-parser/db/shylock.db",
  "init",
]

[tasks.boeupdater-update]
workspace = false
condition = { files_not_exist = [
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/auctions.cbor.zlib",
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/assets.cbor.zlib"
   ] }
command = "cargo"
args = [
  "run",
  "-p",
  "shylock-parser",
  "--release",
  "--bin",
  "boeupdater",
  "--",
  "-d",
  "./shylock-parser/db/shylock.db",
  "update",
]
dependencies = [ "boeupdater-init" ]

[tasks.boeupdater-statistics]
workspace = false
command = "cargo"
args = [
  "run",
  "-p",
  "shylock-parser",
  "--release",
  "--bin",
  "boeupdater",
  "--",
  "-d",
  "./shylock-parser/db/shylock.db",
  "statistics",
]
dependencies = [ "boeupdater-export" ]

[tasks.boeupdater-export]
workspace = false
condition = { files_not_exist = [
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/auctions.cbor.zlib",
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/assets.cbor.zlib"
   ] }
command = "cargo"
args = [
  "run",
  "-p",
  "shylock-parser",
  "--release",
  "--bin",
  "boeupdater",
  "--",
  "-d",
  "./shylock-parser/db/shylock.db",
  "export",
]
dependencies = [ "boeupdater-update" ]

[tasks.clean]
workspace = false
command = "rm"
args = [
  "-f",
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/dist/images/auctions_by_month.svg",
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/auctions.cbor.zlib",
  "${CARGO_MAKE_WORKING_DIRECTORY}/shylock-dominator/assets.cbor.zlib"
]

[tasks.yarn]
workspace = false
command = "yarnpkg"
args = [
  "run",
  "build",
]
#dependencies = [ "clean", "boeupdater-export", "boeupdater-statistics" ]
