name: Pull Request

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.56.1 # MSRV
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-format-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_THUNDERFOREST_API_KEY: "1"
          file_name: .env

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        if: always()
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings -A clippy::unused_unit -A clippy::inconsistent_digit_grouping

  unit_tests:
    name: Unit Tests on ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.56.1 # MSRV

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-unittests-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_THUNDERFOREST_API_KEY: "1"
          file_name: .env

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --workspace

